CREATE OR REPLACE PROCEDURE VALIDATE_TABLES_SP(
    TABLE1_NAME STRING,
    TABLE2_NAME STRING,
    PRIMARY_KEY_COLUMNS STRING DEFAULT NULL,
    TABLE1_ALIAS STRING DEFAULT 'SQL',
    TABLE2_ALIAS STRING DEFAULT 'MDP',
    ENVIRONMENT STRING DEFAULT 'SNOWFLAKE',
    CREATE_TABLES BOOLEAN DEFAULT TRUE,
    STAGE_NAME STRING DEFAULT '@~/'
)
RETURNS STRING
LANGUAGE PYTHON
RUNTIME_VERSION = '3.8'
PACKAGES = ('snowflake-snowpark-python', 'pandas')
HANDLER = 'validate_tables_sp'
AS
$$ 
-- [Paste the entire script here]
$$;
